# Generated by Django 3.2.3 on 2021-06-18 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('template_text', models.TextField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, unique=True)),
                ('name_fa', models.CharField(max_length=50, unique=True)),
                ('server_ip', models.CharField(max_length=50, unique=True)),
                ('server_name', models.CharField(max_length=100, unique=True)),
                ('server_port', models.IntegerField(default=0)),
                ('db_name', models.CharField(max_length=50)),
                ('db_username', models.CharField(max_length=50)),
                ('db_password', models.CharField(max_length=100)),
                ('db_server', models.CharField(max_length=50)),
                ('config_file_name', models.CharField(max_length=60)),
                ('shell_command', models.TextField(max_length=500)),
                ('status_url', models.CharField(default='/', max_length=100)),
                ('swagger_url', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_date', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_manager.commandtemplate')),
            ],
            options={
                'unique_together': {('server_ip', 'server_port'), ('server_name', 'server_ip')},
            },
        ),
        migrations.CreateModel(
            name='QueryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('query_text', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_date', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_manager.databaseinfo')),
            ],
            options={
                'unique_together': {('parent_db', 'name')},
            },
        ),
    ]
