# Generated by Django 3.2.3 on 2021-06-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinfo',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='querymethod',
            name='changed_date',
        ),
    ]
