# Generated by Django 3.2.3 on 2021-06-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0002_auto_20210618_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='server_ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='server_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='databaseinfo',
            unique_together={('server_ip', 'server_port')},
        ),
    ]
