# Generated by Django 3.2 on 2021-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0003_querymethod_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinfo',
            name='status_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='name_fa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='shell_command',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
