# Generated by Django 3.2.3 on 2021-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0004_auto_20210518_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinfo',
            name='db_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='running_pid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='databaseinfo',
            name='shell_command',
            field=models.TextField(max_length=500),
        ),
    ]
