# Generated by Django 3.2.3 on 2021-05-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0005_auto_20210525_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseinfo',
            old_name='status',
            new_name='health',
        ),
    ]
