# Generated by Django 3.2.3 on 2021-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0006_rename_status_databaseinfo_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinfo',
            name='running_pid',
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='docker_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
