# Generated by Django 3.2.3 on 2021-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0007_auto_20210525_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='docker_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
