# Generated by Django 3.2.3 on 2021-05-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0008_alter_databaseinfo_docker_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
