# Generated by Django 3.2.3 on 2021-06-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0009_delete_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='querymethod',
            unique_together={('parent_db', 'name')},
        ),
    ]
