# Generated by Django 3.2.3 on 2021-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0010_alter_querymethod_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinfo',
            name='docker_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
